board/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'boardapp'

urlpatterns = [


    path('<int:pk>/delete/', postdelete, name='postdelete'),

    path('test4/', test2.as_view(), name='test2'),

    path('delete/<int:pk>/', companypostdelete, name='companypostdelete'),

    path('delete/person/<int:pk>/', personalgoaldelete, name='personalgoaldelete'),

    path('delete/department/<int:pk>/', departmentpostdelete, name='departmentpostdelete'),

    path('delete/classification/<int:pk>/', classificationpostdelete, name='classificationpostdelete'),

    path('savetable', views.savetable, name='savetable'),

    path('timeline/',timeline,name='timeline'),

    path('',index, name='index')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('', include('accounts.urls')),
]

board/models.py
from django.contrib.auth.models import User
from django.db import models


# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)


# class Month(models.Model):
#     Month_choices = [
#         ('1', '1'),
#         ('2', '2'),
#         ('3', '3'),
#     ]
#     month = models.CharField(max_length=20, choices=Month_choices, blank=True)


class Board(models.Model):
    month = models.CharField(max_length=20, null=True)
    context = models.CharField(max_length=300, null=True)
    expect = models.FloatField(default=0)
    startdate = models.DateField(auto_now=False, auto_now_add=False, null=True)
    enddate = models.DateField(auto_now=False, auto_now_add=False, null=True)
    time = models.IntegerField(default=0)
    problem = models.CharField(max_length=70, null=True)
    result = models.FloatField(default=0)
    solution = models.CharField(max_length=20, null=True)
    team = models.CharField(max_length=20, null=True)
    level = models.CharField(max_length=20, null=True)
    department = models.CharField(max_length=20, null=True)
    task=models.CharField(max_length=20, null=True)
    num=models.IntegerField(default=0)
    user = models.ForeignKey(User, related_name= 'auths', on_delete=models.DO_NOTHING, blank=True, null=True)

class Company(models.Model):
    title = models.CharField(max_length=20, null=True)
    context = models.CharField(max_length=50, null=True)
    month = models.CharField(max_length=20, null=True)

class Personalgoal(models.Model):
    person = models.CharField(max_length=20, null=True)
    title = models.CharField(max_length=20, null=True)
    context = models.CharField(max_length=50, null=True)
    department = models.CharField(max_length=20, null=True)
    month = models.CharField(max_length=20, null=True)

class Departmentgoal(models.Model):
    department = models.CharField(max_length=20, null=True)
    title = models.CharField(max_length=20, null=True)
    context = models.CharField(max_length=50, null=True)
    month = models.CharField(max_length=20, null=True)

class Classification(models.Model):
    num = models.IntegerField(default=0)
    title = models.CharField(max_length=20, null=True)
    department = models.CharField(max_length=20, null=True)
    month = models.CharField(max_length=20, null=True)

board/forms.py
from django.forms import ModelForm
from .models import *
from django import forms


class ContextForm(ModelForm):
    num = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '20', 'style': 'text-align:center; width:70px;'}))
    task = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'text-align:center; '
                                                                                              'width:200px;'}))
    context = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '300', 'style': 'text-align:center; width:300px;'}))
    expect = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'text-align:center; '
                                                                                                'width:75px;'}))
    startdate = forms.DateField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'style': 'text-align:center; width:180px;', 'id': 'datepicker'}))
    enddate = forms.DateField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'style': 'text-align:center; width:180px;', 'id': 'datepicker1'}))
    time = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'text-align:center; width:65px;'}))
    problem = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '20', 'style': 'text-align:center; width:150px;'}))
    result = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'text-align:center; width:70px;'}))
    solution = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '20', 'style': 'text-align:center; width:100px;'}))
    team = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '20', 'style': 'text-align:center; width:100px;'}))
    level = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '20', 'style': 'text-align:center; width:65px;'}))

    class Meta:
        model = Board
        fields = (
        'num', 'task', 'context', 'expect', 'startdate', 'enddate', 'time', 'problem', 'result', 'solution', 'team',
        'level')


class CompanyForm(ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '30', 'style': 'text-align:center;'}))
    context = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '35', 'style': 'text-align:center;'}))

    class Meta:
        model = Company
        fields = ('title', 'context')


class DepartmentForm(ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '20', 'style': 'text-align:center;'}))
    context = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '50', 'style': 'text-align:center;'}))

    class Meta:
        model = Departmentgoal
        fields = ('title', 'context')


class PersonalgoalForm(ModelForm):
    person = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '15', 'style': 'text-align:center;'}))
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '20', 'style': 'text-align:center;'}))
    context = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '50', 'style': 'text-align:center;'}))

    class Meta:
        model = Personalgoal
        fields = ('person', 'title', 'context')


class ClassificationForm(ModelForm):
    num = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'text-align:center'}))
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '20', 'style': 'text-align:center;'}))

    class Meta:
        model = Classification
        fields = ['num', 'title']

board/views.py
from datetime import datetime
from hashlib import new
from tkinter import messagebox

from MySQLdb import Date
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.db import models
# Create your views here.
from django.urls import reverse
from django.utils import timezone
from django.utils.dateformat import DateFormat
from django.utils.decorators import method_decorator

from django.views import View
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DeleteView

from .decorator import login_message_required
from .forms import *
import json

def index(request):
    return render(request, 'index.html')

# 완성본 게시판
class test2(ListView):

    @method_decorator(login_message_required)
    def get(self, request):

        # mainboard
        contextForm = ContextForm
        department_text = request.GET.get('department')
        month_text = request.GET.get('month')
        if month_text is None:
            month_text = DateFormat(datetime.now()).format('m')
        if department_text is None:
            department_text = "개발"
        board_list = Board.objects.filter(month=month_text, department=department_text).order_by("user")

        # 회사목표
        companyForm = CompanyForm
        company_list = Company.objects.all()

        # 부서목표
        departmentForm = DepartmentForm
        department_list = Departmentgoal.objects.filter(department=department_text)

        # 개별목표
        personalgoalForm = PersonalgoalForm
        personalgoal_list = Personalgoal.objects.filter(department=department_text)

        # 분류
        classificationForm = ClassificationForm
        classification_list = Classification.objects.filter(department=department_text)

        # board_list 페이징 처리
        page = request.GET.get('page', '1')
        paginator = Paginator(board_list, '10')
        page_obj = paginator.page(page)

        context = {
            # company context
            'company_list': company_list,
            'companyForm': companyForm,

            # test2 context
            'contextForm': contextForm,
            'board_list': page_obj,
            'month_text': month_text,
            'department_text': department_text,

            # personal context
            'personalgoalForm': personalgoalForm,
            'personalgoal_list': personalgoal_list,

            # departmentgoal context
            'departmentForm': departmentForm,
            'department_list': department_list,

            # classification context
            'classificationForm': classificationForm,
            'classification_list': classification_list,
        }
        return render(request, 'test1.html', context)

    def post(self, request):

        # 월 - 게시판
        if request.method == 'POST' and 'attr_name' in request.POST:

            board = Board(
                context=request.POST['context'],
                num=request.POST['num'],
                task=request.POST['task'],
                expect=request.POST['expect'],
                startdate=request.POST['startdate'],
                enddate=request.POST['enddate'],
                time=request.POST['time'],
                problem=request.POST['problem'],
                result=request.POST['result'],
                solution=request.POST['solution'],
                team=request.POST['team'],
                level=request.POST['level'],
            )

            month_text = request.GET.get('month')
            department_text = request.GET.get('department')
            if month_text is None:
                month_text = DateFormat(datetime.now()).format('m')
            if department_text is None:
                department_text = "개발"
            board.department = department_text
            board.month = month_text
            user = request.user
            username = User.objects.get(username=user)
            board.user = username
            context_text = request.POST.get('context')
            same_context = Board.objects.filter(context=context_text, month=month_text, department=department_text)

            try:
                if len(same_context) == 0:
                    board.save()
                    return redirect(request.META.get('HTTP_REFERER'))
                else:
                    messages.warning(request, " 세부테스크의 내용이 중복입니다. 다른 내용으로 바꿔주세요.")
                    return redirect(request.META.get('HTTP_REFERER'))
            except ValueError:
                messages.warning(request, " 숫자여야 합니다. ")
                return redirect(request.META.get('HTTP_REFERER'))


        # 회사

        if request.method == 'POST' and 'attr_name2' in request.POST:
            company = Company(
                title=request.POST['title'],
                context=request.POST['context'],
            )
            company.save()
            return redirect(request.META.get('HTTP_REFERER'))


        # 개인목표

        if request.method == 'POST' and 'attr_name3' in request.POST:
            personalgoal = Personalgoal(
                person=request.POST['person'],
                title=request.POST['title'],
                context=request.POST['context'],
            )
            department_text = request.GET.get('department')
            if department_text is None:
                department_text = "개발"
            personalgoal.department = department_text
            personalgoal.save()
            return redirect(request.META.get('HTTP_REFERER'))


        # 부서 목표

        if request.method == 'POST' and 'attr_name4' in request.POST:

            departmentgoal = Departmentgoal(
                title=request.POST['title'],
                context=request.POST['context'],
            )

            department_text = request.GET.get('department')
            if department_text is None:
                department_text = "개발"
            departmentgoal.department = department_text
            departmentgoal.save()
            return redirect(request.META.get('HTTP_REFERER'))


        # 분류
        if request.method == 'POST' and 'attr_name5' in request.POST:
            classification = Classification(
                num=request.POST['num'],
                title=request.POST['title'],
            )
            department_text = request.GET.get('department')
            if department_text is None:
                department_text = "개발"
            classification.department = department_text
            try:
                classification.save()
                return redirect(request.META.get('HTTP_REFERER'))
            except ValueError:
                messages.warning(request, " 숫자여야 합니다. ")
                return redirect(request.META.get('HTTP_REFERER'))


# 게시판 수정 삭제

def postdelete(request, pk):
    board = Board.objects.get(pk=pk)
    board.delete()
    return redirect(request.META.get('HTTP_REFERER'))


# 회사 삭제

def companypostdelete(request, pk):
    company = Company.objects.get(pk=pk)
    company.delete()
    return redirect(request.META.get('HTTP_REFERER'))


# 개별목표 삭제

def personalgoaldelete(request, pk):
    personalgoal = Personalgoal.objects.get(pk=pk)
    personalgoal.delete()
    return redirect(request.META.get('HTTP_REFERER'))


# 부서 삭제

def departmentpostdelete(request, pk):
    departmentgoal = Departmentgoal.objects.get(pk=pk)
    departmentgoal.delete()
    return redirect(request.META.get('HTTP_REFERER'))


# 분류 삭제

def classificationpostdelete(request, pk):
    classification = Classification.objects.get(pk=pk)
    classification.delete()
    return redirect(request.META.get('HTTP_REFERER'))


@csrf_exempt
def savetable(request):
    # main Board
    id = request.POST.get('id', '')
    type = request.POST.get('type', '')
    value = request.POST.get('value', '')
    board = Board.objects.get(id=id)
    if type == "context":
        board.context = value
    if type == "expect":
        board.expect = value
    if type == "startdate":
        board.startdate = value
    if type == "enddate":
        board.enddate = value
    if type == "time":
        board.time = value
    if type == "problem":
        board.problem = value
    if type == "result":
        board.result = value
    if type == "solution":
        board.solution = value
    if type == "team":
        board.team = value
    if type == "level":
        board.level = value
    board.save()
    return JsonResponse({"success": "Updated!!"})


def timeline(request):
    department_text = request.GET.get('department')
    month_text = request.GET.get('month')
    if month_text is None:
        month_text = DateFormat(datetime.now()).format('m')
    if department_text is None:
        department_text = "개발"

    board_list = Board.objects.filter(month=month_text, department=department_text).order_by("startdate")
    department_list = Departmentgoal.objects.filter(department=department_text)
    personalgoal_list = Personalgoal.objects.filter(department=department_text)
    classification_list = Classification.objects.filter(department=department_text)
    company_list = Company.objects.all()

    data = []
    for i in board_list:
        data.append([i.context, i.context, str(i.user), str(i.startdate), str(i.enddate), None, i.result * 100, None])

    modified_data = json.dumps(data, ensure_ascii=False)

    context = {
        'values': modified_data,
        'board_list': board_list,
        'month_text':month_text,
        'department_text': department_text,
        'classification_list': classification_list,
        'department_list': department_list,
        'personalgoal_list': personalgoal_list,
        'company_list': company_list,
    }

board/templates/timeex.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<html>
<head>
    <div>
        <img src="https://cdn.pixabay.com/photo/2014/04/03/00/41/house-309113_1280.png" onClick="location.href={% url 'boardapp:test2'%}" style="width:50px; height:50px; cursor:pointer; margin-left:3%;">
        <form method="get" action="" class="form" style="margin-left:2%; margin-top:10px;">
            <select name="month" id="id_month">
                <option value="0" selected>월 선택</option>
                <option value="01">1월</option>
                <option value="02">2월</option>
                <option value="03">3월</option>
                <option value="04">4월</option>
                <option value="05">5월</option>
                <option value="06">6월</option>
                <option value="07">7월</option>
                <option value="08">8월</option>
                <option value="09">9월</option>
                <option value="10">10월</option>
                <option value="11">11월</option>
                <option value="12">12월</option>
            </select>
        </form>
        <h1 style="color:gray; margin-left:130px; margin-top:-70px; font-family: 'Jua', sans-serif; font-size:3.5em; font-size:3.5em;">{{department_text}}team</h1>
        <div>
            <form method="get" class="forms">
                <button type="button" class="btn btn-outline-primary" style="font-family: 'Jua', sans-serif; font-size:2rem; margin-top:-120px; margin-left:470px;" name="department" value="개발" onClick="location.href='/timeline/?month={{ month_text }}&department=개발'">개발팀</button>
                <button type="button" class="btn btn-outline-warning" style="font-family: 'Jua', sans-serif; font-size:2rem; margin-top:-120px;" name="department" value="경영/기획" onClick="location.href='/timeline/?month={{ month_text }}&department=경영/기획'">경영/기획팀</button>
                <button type="button" class="btn btn-outline-success" style="font-family: 'Jua', sans-serif; font-size:2rem; margin-top:-120px;" name="department" value="영업" onClick="location.href='/timeline/?month={{ month_text }}&department=영업'">영업팀</button>
            </form>
        </div>

        <img onclick="info_btn()" src="https://cdn.pixabay.com/photo/2017/06/13/12/54/furthermore-2398784_960_720.png" style="width:30px; height:30px; cursor:pointer; margin-top:-100px; margin-left:900px;">
        <div id="info" style="display:none; margin-left:20px;">
            <div style="font-family: 'Jua', sans-serif; color:#606060; display:flex; box-sizing:border-box; max-width:30%;">
                <table>
                    <thead>
                        <tr>
                            <th colspan="2">회사목표</th>
                        </tr>
                    </thead>
                {% for company in company_list %}
                    <tbody>
                        <tr>
                            <td>{{company.title}}</td>
                            <td>{{company.context}}</td>
                            <br>
                        </tr>
                    </tbody>
                {% endfor %}
                </table>
            </div>
            <div style="font-family: 'Jua', sans-serif; color:#606060; display:flex; box-sizing:border-box; max-width:30%;">
                <table>
                    <thead>
                        <tr>
                            <th colspan="2">팀목표</th>
                        </tr>
                    </thead>
                {% for departmentgoal in department_list %}
                    <tbody>
                        <tr>
                            <td>{{departmentgoal.title}}</td>
                            <td>{{departmentgoal.context}}</td>
                            <br>
                        </tr>
                    </tbody>
                {% endfor %}
                </table>
            </div>
            <div style="font-family: 'Jua', sans-serif; color:#606060; display:flex; box-sizing:border-box; max-width:30%;">
                <table>
                    <thead>
                        <tr>
                            <th colspan="4">개인목표</th>
                        </tr>
                    </thead>
                    {% for personalgoal in personalgoal_list %}
                    <tbody>
                        <tr>
                            <td>{{personalgoal.person}}</td>
                            <td>{{personalgoal.title}}</td>
                            <td>{{personalgoal.context}}</td>
                            <td>{{personalgoal.departmentgoal}}</td>
                            <br>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
            <div style="font-family: 'Jua', sans-serif; color:#606060; display:flex; box-sizing:border-box; max-width:10%;">
                <table>
                    <thead>
                        <tr>
                            <th colspan="2">분류</th>
                        </tr>
                    </thead>
                    {% for classification in classification_list %}
                    <tbody>
                        <tr>
                            <td>{{classification.num}}</td>
                            <td>{{classification.title}}</td>
                            <br>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

    <br>
    <br>

    <h2 style="font-family: 'Nanum Gothic', sans-serif; font-size:1.5em; border-left: 5px solid #1f3a93; margin-left:1%; margin-top:-40px;">&nbsp;&nbsp;{{ month_text }}월 OKR </h2>
    <div>
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script type="text/javascript">
    google.charts.load('current', {'packages':['gantt']});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = new google.visualization.DataTable();
      var arr = {{values|safe}};
      data.addColumn('string', 'Task ID');
      data.addColumn('string', 'Task Name');
      data.addColumn('string', 'name');
      data.addColumn('date', 'Start Date');
      data.addColumn('date', 'End Date');
      data.addColumn('number', 'Duration');
      data.addColumn('number', 'Percent Complete');
      data.addColumn('string', 'Dependencies');
      var array = new Array();
      for(var i=0; i < arr.length; i++){
        array[i] = [arr[i][0] , arr[i][1] , arr[i][2], new Date(arr[i][3]),new Date(arr[i][4]), null, arr[i][6], null]
      }
      console.log(array);
      data.addRows(array);
      console.log(array);
      var options = {
        height: arr.length*40,
        gantt: {
          trackHeight: 30.23
        }
      };
      var chart = new google.visualization.Gantt(document.getElementById('chart_div'));
      chart.draw(data, options);
    }
  </script>
    </div>
</head>
<body>



<div class="graph" style="display:flex;">
<!--    첫번째-->
    <div>
        <table id="left" style="text-align:center;">
            <thead>
            <th style="width:60px; height:20px; border-bottom: 1px solid; border-color:#E0E0E0; background-color:#fec5bb">분류</th>
            <th style="width:400px; height:20px; border-bottom: 1px solid; border-color:#E0E0E0; background-color:#fcd5ce;">테스크</th>
            <th style="width:55px; height:30px; border-bottom: 1px solid; border-color:#E8E8E8; background-color:#fae1dd;">예상</th>
            </thead>
            <tbody>
            {% for board in board_list %}
            <tr height="30">
                <td style="width:50px; border-bottom: 1.4px solid; border-style:thin; border-color:#E0E0E0; font-size:1.0em;">{{board.num}}</td>
                <td style="width:280px; border-bottom: 1.4px solid; border-style:thin; border-color:#E0E0E0; font-size:1.0em;">{{board.task}}</td>
                <td style="width:50px; border-bottom: 1.4px solid; border-style:thin; border-color:#E0E0E0; font-size:1.0em;">{{board.expect}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        <table>
            <thead>
               <th style="width:1000px; margin-left:200px; margin-top:2px; background-color:#f8edeb; height:30px; text-align:center;">세부테스크 및 시작/끝일정</th>
            </thead>
        </table>
        <div id="chart_div" style="margin-top:-0px;height:20%; width:100%;"></div>
    </div>
    <div>
        <table id="right" style="text-align:center;">
            <thead>
            <th style="width:70px; height:20px; border-bottom: 1.5px solid; border-color:#E0E0E0; background-color:#e8e8e4;">시간</th>
            <th style="width:300px; height:30px; border-bottom: 1px solid; border-color:#E8E8E8; background-color:#d8e2dc;">진행문제점</th>
            <th style="width:200px; height:20px; border-bottom: 1.5px solid; border-color:#E0E0E0; background-color:#ffe5d9;">해결방안</th>
            <th style="width:140px; height:20px; border-bottom: 1.5px solid; border-color:#E0E0E0; background-color:#ffd7ba;">팀</th>
            <th style="width:80px; height:20px; border-bottom: 1px solid; border-color:#E0E0E0; background-color:#fec89a;">Lv</th>
            </thead>
            <tbody>
            {% for board in board_list %}
            <tr height="30">
                <td style="width:50px; border-bottom: 1.4px solid; border-style:thin; border-color:#E0E0E0; font-size:1.0em;">{{board.time}}</td>
                <td style="width:300px; border-bottom: 1.4px solid; border-style:thin; border-color:#E0E0E0; font-size:1.0em;">{{board.problem}}</td>
                <td style="width:200px; border-bottom: 1.4px solid; border-style:thin; border-color:#E0E0E0; font-size:1.0em;">{{board.solution}}</td>
                <td style="width:110px; border-bottom: 1.4px solid; border-style:thin; border-color:#E0E0E0; font-size:1.0em;">{{board.team}}</td>
                <td style="width:80px; border-bottom: 1.4px solid; border-style:thin; border-color:#E0E0E0; font-size:1.0em;">{{board.level}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!--    세번째-->
</div>
</body>
</html>
<script>
  function info_btn(){
      if($('#info').css('display') == 'none'){
      $('#info').show();
      document.getElementById('info').style.display = 'flex';
      document.getElementById('h2').style.marginTop = '-30px';
      document.getElementByClassName('graph').style.marginTop = '-30px';
    }else{
      $('#info').hide();
      document.getElementById('h2').style.marginTop = '';
      document.getElementByClassName('graph').style.marginTop = '';
    }
    }
</script>
<script>
    $(document).ready(function() {
        $( "select[name=month]" ).val( "{{ month_text }}" );
        $('select[name=month]').change(function () {
            console.log($('select[name=month]').val());
            month = $('select[name=month]').val();
            $('.form').submit();
        });
    });
    $(document).ready(function() {
        $('button[name=department]').change(function () {
            console.log($('button[name=department]').val());
            department = $('button[name=department]').val();
            $('.forms').attr('action', "/test4/?month={{month_text}}").submit();
        });
    });
</script>
<script>
    $(document).ready(function(){
  $('.large').click(function(){
    document.getElementById('chart_div').style.display = 'block';
    document.getElementById('table').style.marginLeft = '-570px';
    document.getElementById('th').style.width = '600px';
    });
  $('.small').click(function(){
    document.getElementById('chart_div').style.display = 'none';
    document.getElementById('th').style.width = '';
    document.getElementById('table').style.marginLeft = '-333px';
    document.getElementById('th').style.width = '60px';
    });
});
</script>
{% endblock %}